name: Commit sanity

on: [push]

jobs:
  check_message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Commit message check
        uses: ./.github/actions/commit_message_checker
