name: Unit Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: npm run test:nowatch
      - name: Hello world action step
        uses: ./.github/actions/jira_id_checker # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: "Gurra"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
