name: Unit Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: npm run test:nowatch
      - name: Notify slack
        uses: gustavjorlov/slacker@1d17481
        with:
          message: Yey, tests are passing!
          slack-url: https://hooks.slack.com/services/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
