name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: npm run test -- * --no-watch
