name: Unit Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: npm run test:nowatch
  notify_slack:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Notify slack
        uses: gustavjorlov/slacker@e74d5f0
        with:
          message: "Yey, tests are passing!"
          slack-url: ${{secrets.SLACK_URL}}
